# Generated by Django 5.1.7 on 2025-06-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagemcoletas_imagemperfil_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagemcoletas',
            table='imagens_coleta',
        ),
    ]
